---
title: "KEGG pathway database"
author: "Sergio Picart-Armada"
date: "23 January 2017"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(KEGG.db)
library(magrittr)
library(igraph)
library(plyr)

source("helpers/sanitise.R")
load("biogrid2011.RData")

names.genes <- V(biogrid2011)$name
```

Newer version of KEGG, 2018
```{r}
df.kegg2018 <- read.table(
  "kegg/kegg2018_pathways.txt", 
  stringsAsFactors = FALSE
)
df.kegg2018[, 1] %<>% sanitise(category = "pathway", organism = "hsa")
df.kegg2018[, 2] %<>% sanitise(category = "gene", organism = "hsa")
info.kegg2018 <- readLines("kegg/kegg2018_info.txt")

names2018 <- unique(df.kegg2018[, 1])
```


Older version of KEGG, 2011
```{r, message=FALSE, warning=FALSE}
# Version and date
info.kegg2011 <- KEGG.db::KEGG_dbInfo()
info.kegg2011 <- setNames(info.kegg2011$value, info.kegg2011$name)
info.kegg2011

kegg2011 <- as.list(KEGGPATHID2EXTID)
names2011 <- names(kegg2011)[grepl("hsa\\d{5}", names(kegg2011))] %>% sort
```

Concordance with pathway names
```{r}
length(names2011)
length(names2018)
names.common <- intersect(names2011, names2018)
length(names.common)
```

Intersect pathways with network and make sure that pathways have at least one gene in 2011 and 2018. Make sure as well that there is a change 
```{r}
kegg2011 <- lapply(
  kegg2011[names.common],
  function(path) sort(intersect(path, names.genes)))

kegg2018 <- plyr::dlply(
  df.kegg2018, 
  "V1", 
  function(path) sort(intersect(path$V2, names.genes)))[names.common]
attributes(kegg2018) <- list(names = names(kegg2018))

# Now both have the same ordenation, so...
# pathways.nonempty <- (plyr::laply(kegg2011, length) != 0) & 
  # (plyr::laply(kegg2018, length) != 0)

pathways.valid <- plyr::laply(
  names(kegg2011), 
  function(n) {
    p_old <- kegg2011[[n]]
    p_new <- kegg2018[[n]]
    
    if (length(p_old) == 0) return(FALSE)
    length(setdiff(p_new, p_old)) > 0
  }
)

kegg2011 <- kegg2011[pathways.valid]
kegg2018 <- kegg2018[pathways.valid]

length(unlist(kegg2011))
length(unlist(kegg2018))
```

Save the pathways

```{r}
comment(kegg2011) <- info.kegg2011
save(kegg2011, 
     file = "../data/kegg2011.RData", 
     compress = "xz")
comment(kegg2018) <- info.kegg2018
save(kegg2018, 
     file = "../data/kegg2018.RData", 
     compress = "xz")
```

On a separate matter, load the KEGG data used for DLBCL (slightly different version) and save its tables

```{r}
keggdlbcl <- read.table(
  "kegg_dlbcl/kegg_gene2pathway.txt", 
  stringsAsFactors = FALSE
)
keggdlbcl[, 1] %<>% sanitise(category = "pathway", organism = "hsa")
keggdlbcl[, 2] %<>% sanitise(category = "gene", organism = "hsa")

info.keggdlbcl <- readLines("kegg_dlbcl/kegg_info.txt")

head(keggdlbcl)
```

Number of pathways:

```{r}
dim(keggdlbcl)
length(unique(keggdlbcl[, 1]))
```


```{r}
comment(keggdlbcl) <- info.keggdlbcl
save(keggdlbcl, 
     file = "../data/keggdlbcl.RData", 
     compress = "xz")
```

